@RegPage/Pages/AllPages/Content.cshtml.cs
using _RegPage.Data;
using _RegPage.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Diagnostics;
using System.Globalization;

namespace _RegPage.Pages.AllPages
{

    public class ContentModel : PageModel
    {

        public void OnGet()
        {
            
        }
    }
}

@RegPage/Pages/AllPages/Delete.cshtml.cs
using _RegPage.Data;
using _RegPage.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace _RegPage.Pages.AllPages
{
    [BindProperties]
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public Credentials Credentials { get; set; }

        public DeleteModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public void OnGet(string Email)
        {


            Credentials = _db.Credentials.Find(Email);
        }

        public async Task<IActionResult> OnPost()
        {
             _db.Credentials.Remove(Credentials);
             await _db.SaveChangesAsync();
             return RedirectToPage("ViewDetails");
        }
        
    }
}

@RegPage/Pages/AllPages/Edit.cshtml.cs
using _RegPage.Data;
using _RegPage.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Runtime.InteropServices;

namespace _RegPage.Pages.AllPages
{
    [BindProperties]
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public Credentials Credentials{ get; set; }

        public EditModel(ApplicationDbContext db)
        {
            _db = db;
        }
       
        public void OnGet(string Email)
        {
            

            Credentials = _db.Credentials.Find(Email);
        }

        public async Task<IActionResult> OnPost()
        {
            if(Credentials.Password != Credentials.ConfPassword)
            {
                ModelState.AddModelError("Credentials.ConfPassword", "Confirm password should be same as password");
            }



            if (ModelState.IsValid)
            {
                _db.Credentials.Update(Credentials);
                await _db.SaveChangesAsync();
                return RedirectToPage("ViewDetails");
            }
            return Page();
        }
    }
}

@RegPage/Pages/AllPages/Login.cshtml.cs
using _RegPage.Data;
using _RegPage.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace _RegPage.Pages.AllPages
{
    public class LoginModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string Email { get; set; }


        [BindProperty]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public Credentials Credentials { get; set; }

        

        public LoginModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPost()
        {

            String findEmail = _db.Credentials.FirstOrDefault(x => x.Email == Email)?.Email??"";
            String findPassword = _db.Credentials.Where(x => x.Email == findEmail).FirstOrDefault()?.Password??"";
            if (findEmail == ""|| findPassword =="")
            {

                ModelState.AddModelError(findEmail, "Email not found, Create new account");

            }
            else if (Email != findEmail || Password != findPassword)
            {
                ModelState.AddModelError(findPassword, "Wrong Credentials");

            }
            if (!ModelState.IsValid)
            {
                return Page();
            }
            TempData["UserName"] = _db.Credentials.FirstOrDefault(x => x.Email == Email)?.FullName ?? "";

            return RedirectToPage("/AllPages/Content");
        }
    }
}

@RegPage/Pages/AllPages/LoginLayout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace _RegPage.Pages.AllPages
{
    public class LayoutLoginModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

@RegPage/Pages/AllPages/Register.cshtml.cs
 using _RegPage.Data;
using _RegPage.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace _RegPage.Pages.AllPages
{
    [BindProperties]
    public class RegisterModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public Credentials Credentials { get; set; }

        public RegisterModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public void OnGet()
        {


        }
        public async Task<IActionResult> OnPost(Credentials Credentials)
        {
            if (Credentials.IsChecked == false)
            {
                ModelState.AddModelError("Credentials.IsChecked", "Mark this feild");

            }

            string isFound = _db.Credentials.FirstOrDefault(x=> x.Email == Credentials.Email)?.Email??"";

            if (isFound != "") {
                ModelState.AddModelError("Credentials.Email", "User already exists, Login to your account");
            }

            if(Credentials.Password != Credentials.ConfPassword)
            {
                ModelState.AddModelError("Credentials.ConfPassword", "Confirm password should be same as Password");
            }
            if (ModelState.IsValid)
            {
                await _db.Credentials.AddAsync(Credentials);
                await _db.SaveChangesAsync();
                return RedirectToPage("/AllPages/Login");
            }
            else
            {
                return Page();
            }
        }
    }
}

@RegPage/Pages/AllPages/ViewDetails.cshtml.cs
using _RegPage.Data;
using _RegPage.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ClosedXML.Excel;
using System.IO;
using System.Data;
using Microsoft.Extensions.Configuration;
using System.Runtime.InteropServices;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.EntityFrameworkCore;

namespace _RegPage.Pages.AllPages
{
    [BindProperties]
    public class ViewDetailsModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        private readonly IConfiguration _config;

        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }

        [BindProperty]

        public string nameSort { get; set; }

        [BindProperty]

        public string dateSort { get; set; }

        [BindProperty]

        public string genSort { get; set; }

        [BindProperty]

        public string modSort { get; set; }

        public PaginatedList<Credentials> Credentials { get; set; }

        public ViewDetailsModel(ApplicationDbContext db, IConfiguration configuration)
        {
            _db = db;
            _config = configuration;
        }
        
        public int pn { get; set; }
        public async Task OnGetAsync(string sortOrder, int? pageIndex)
        {

            IQueryable<Credentials> Cred = from s in _db.Credentials select s;
           

            if (!string.IsNullOrEmpty(SearchString))
            {
                Cred = Cred.Where(x => x.FullName.ToLower().Contains(SearchString.ToLower()) || x.Email.ToLower().Contains(SearchString.ToLower()) || x.MobileNumber.Contains(SearchString));
            }
            if (SearchString != null)
            {
                pageIndex = 1;
                pn = 1;

            }

            if(!Cred.Any())
            {
                TempData["ErrorMessage"] = "User not found!";
            }


            nameSort = sortOrder == "name_asec" ? "name_desc" : "name_asec";
            dateSort = sortOrder == "date_asec" ? "date_desc" : "date_asec";
            genSort = sortOrder == "Female" ? "Male" : "Female";
            modSort = sortOrder == "m_asec" ? "m_desc" : "m_asec";
            

            switch (sortOrder)
            {
                case "name_asec":
                    Cred = Cred.OrderBy(s => s.FullName);
                    break;
                case "name_desc":
                    Cred = Cred.OrderByDescending(s => s.FullName);
                    break;
                case "date_desc":
                    Cred = Cred.OrderByDescending(s => s.DOB);
                    break;
                case "date_asec":
                    Cred = Cred.OrderBy(s => s.DOB);
                    break;
                case "Male":
                    Cred = Cred.Where(s => s.Gender.Contains("Male"));
                    break;
                case "Female":
                    Cred = Cred.Where(s => s.Gender.Contains("Female"));
                    break;
                case "m_asec":
                    Cred = Cred.OrderBy(s => s.ModDate);
                    break;
                case "m_desc":
                    Cred = Cred.OrderByDescending(s => s.ModDate);
                    break;
                default:
                    Cred = Cred.OrderBy(s => s.Email);
                    break;
            }
            
            var pageSize = _config.GetValue("PageSize", 4);
            Credentials = await PaginatedList<Credentials>.CreateAsync(Cred, pageIndex ?? 1, pageSize);
            
            
        }

        public FileResult OnPostExport()
        {
            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[7] { new DataColumn("Email"), new DataColumn("FullName"),new DataColumn("Mobile Number"),new DataColumn("Salutation"), new DataColumn("Gender"), new DataColumn("DOB"), new DataColumn("Password") });

            var expData = from exp in this._db.Credentials.Take(20) select exp;
           

            foreach(var exp  in expData)
            {
                dt.Rows.Add(exp.Email, exp.FullName, exp.MobileNumber, exp.Salutation, exp.Gender, exp.DOB, exp.Password);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Grid.xlsx");
                }
            }
        }

        
    }
}

@RegPage/Pages/AllPages/Content.cshtml
@page
@model _RegPage.Pages.AllPages.ContentModel
@{
    Layout = "LoginLayout.cshtml";
}
<br />

<div class="text-center">
    <h3>Welcome @TempData["UserName"]!</h3>
</div>

<br />

@RegPage/Pages/AllPages/Delete.cshtml
@page
@model _RegPage.Pages.AllPages.DeleteModel
@{
    Layout = "LoginLayout.cshtml";
}



<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Delete Credentials</h3>
                </div>
                <div class="card-body">
                    <form method="post">

                        <div class="row mb-3">
                            <label asp-for="Credentials.Salutation" class="col-sm-4 col-form-label">Salutation</label>
                            <div class="col-sm-8">
                                <select class="form-select" asp-for="Credentials.Salutation" >
                                    <option value="Mr" asp-for="Credentials.Salutation" >Mr</option>
                                    <option value="Ms" asp-for="Credentials.Salutation">Ms</option>
                                    <option value="Mrs" asp-for="Credentials.Salutation">Mrs</option>
                                </select>
                                <span asp-validation-for="Credentials.Salutation" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label asp-for="Credentials.FullName" class="col-sm-4 col-form-label">FullName</label>
                            <div class="col-sm-8">
                                <input class="form-control" asp-for="Credentials.FullName"  />
                                <span asp-validation-for="Credentials.FullName" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label asp-for="Credentials.Email" class="col-sm-4 col-form-label">Email</label>
                            <div class="col-sm-8">
                                <input class="form-control" asp-for="Credentials.Email"  />
                                <span asp-validation-for="Credentials.Email" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label asp-for="Credentials.MobileNumber" class="col-sm-4 col-form-label"></label>
                            <div class="col-sm-8">
                                <input class="form-control" asp-for="Credentials.MobileNumber"  />
                                <span asp-validation-for="Credentials.MobileNumber" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label asp-for="Credentials.DOB" class="col-sm-4 col-form-label">Date of Birth</label>
                            <div class="col-sm-8">
                                <input type="date" class="form-control" asp-for="Credentials.DOB"  />
                                <span asp-validation-for="Credentials.DOB" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label asp-for="Credentials.Gender" class="col-sm-4 col-form-label"></label>
                            <div class="col-sm-8">
                                <label>Male</label>
                                <input type="radio" value="Male" asp-for="Credentials.Gender" style="margin-right: 20px;"  />
                                <label>Female</label>
                                <input type="radio" value="Female" asp-for="Credentials.Gender"  />
                            </div>
                            <span asp-validation-for="Credentials.Gender" class="text-danger"></span>
                        </div>

                        <hr />

                        <div class="row mb-1">
                            <div class="col-6 mb-1">
                                <button type="submit" class="btn btn-danger rounded-pill align-content-center w-100 ">Delete</button>
                            </div>
                            <div class="col-6 mb-1">
                                <a asp-page="ViewDetails" class="btn btn-primary rounded-pill align-content-center w-100">Back to List</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@RegPage/Pages/AllPages/Edit.cshtml
@page
@model _RegPage.Pages.AllPages.EditModel
@{
    Layout = "LoginLayout.cshtml";
}



<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center">Update Credentials</h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        <div class="row mb-3">
                            <label asp-for="Credentials.Salutation" class="col-sm-4 col-form-label">Salutation</label>
                            <div class="col-sm-8">
                                <select class="form-select" asp-for="Credentials.Salutation">
                                    <option value="Mr" asp-for="Credentials.Salutation">Mr</option>
                                    <option value="Ms" asp-for="Credentials.Salutation">Ms</option>
                                    <option value="Mrs" asp-for="Credentials.Salutation">Mrs</option>
                                </select>
                                <span asp-validation-for="Credentials.Salutation" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label asp-for="Credentials.FullName" class="col-sm-4 col-form-label">FullName</label>
                            <div class="col-sm-8">
                                <input class="form-control" asp-for="Credentials.FullName" />
                                <span asp-validation-for="Credentials.FullName" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label asp-for="Credentials.Email" class="col-sm-4 col-form-label">Email</label>
                            <div class="col-sm-8">
                                <input class="form-control" asp-for="Credentials.Email" readonly/>
                                <span asp-validation-for="Credentials.Email" class="text-danger"></span>
                            </div>
                        </div> 

                        <div class="row mb-3">
                            <label asp-for="Credentials.MobileNumber" class="col-sm-4 col-form-label"></label>
                            <div class="col-sm-8">
                                <input class="form-control" asp-for="Credentials.MobileNumber" />
                                <span asp-validation-for="Credentials.MobileNumber" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label asp-for="Credentials.DOB" class="col-sm-4 col-form-label">Date of Birth</label>
                            <div class="col-sm-8">
                                <input type="date" class="form-control" asp-for="Credentials.DOB" />
                                <span asp-validation-for="Credentials.DOB" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label asp-for="Credentials.Gender" class="col-sm-4 col-form-label"></label>
                            <div class="col-sm-8">
                                <label>Male</label>
                                <input type="radio" value="Male" asp-for="Credentials.Gender" style="margin-right: 20px;" />
                                <label>Female</label>
                                <input type="radio" value="Female" asp-for="Credentials.Gender" />
                            </div>
                            <span asp-validation-for="Credentials.Gender" class="text-danger"></span>
                        </div>

                        <div class="row mb-3">
                            <label asp-for="Credentials.Password" class="col-sm-4 col-form-label" >Password</label>
                            <div class="col-sm-8">
                                <input class="form-control" asp-for="Credentials.Password"  />
                                <span asp-validation-for="Credentials.Password" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label asp-for="Credentials.ConfPassword" class="col-sm-4 col-form-label">Confirm Password</label>
                            <div class="col-sm-8">
                                <input class="form-control" asp-for="Credentials.ConfPassword" />
                                <span asp-validation-for="Credentials.ConfPassword" class="text-danger"></span>
                            </div>
                        </div>
                        <div>
                            <input type="checkbox" asp-for="Credentials.IsChecked" readonly>  I accept the terms and conditions

                            <span asp-validation-for="Credentials.IsChecked" class="text-danger"></span>
                        </div> 
                       

                       <hr />
                       
                        <div class="row mb-1">
                            <div class="col-6 mb-1">
                                <button type="submit" class="btn btn-success rounded-pill align-content-center w-100">Update</button>
                            </div>
                            <div class="col-6 mb-1">
                                <a asp-page="ViewDetails" class="btn btn-primary rounded-pill align-content-center w-100">Back to List</a>

                            </div>


                        </div>

                    </form>
                </div>
            
            </div>
        </div>
    </div>
</div>

@RegPage/Pages/AllPages/Login.cshtml
@page
@model _RegPage.Pages.AllPages.LoginModel
@{
  
}


<div>
    <br /><br /><br />
    <div class="container p-3 col-4 card">
        <div class="card-body ">
            <h2 class="fw-bold text-center">Sign In</h2>
            <hr />
            <br />
            
            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div> 

                <input asp-for="Email" placeholder="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span><br />

                <input asp-for="Password" placeholder="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span><br />

                <button class="btn btn-success w-80 rounded-pill">Login</button><br /> <br />

                <input type="checkbox" class="form-check-input text-primary" />

                <label class="form-check-label ">&nbsp; Stay signed in</label><br /> <br />

                <a class="btn btn-primary rounded-pill w-100" asp-page="/AllPages/Register">Create an account</a>
            </form>
        </div>
    </div>
</div>

@RegPage/Pages/AllPages/LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _RegPage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_RegPage.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="ViewDetails">User Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="Login">Logout</a>
                        </li>

                       
                     </ul>
                </div>
            </div>
        </nav> 
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

@RegPage/Pages/AllPages/ViewDetails.cshtml
@page
@model _RegPage.Pages.AllPages.ViewDetailsModel
@{
    Layout = "LoginLayout.cshtml";
}

<div >
<div class="container">
    <div class="row pt-2">
        <div class="col">
            <h2 class="text-primary">All User details</h2>
        </div>
        <hr />
    </div>


    <br/>
        @{
            if(TempData.ContainsKey("ErrorMessage"))
            {
                <div class="alert alert-danger">
                @TempData["ErrorMessage"]
                </div>
            }
        }
    <div class="d-flex justify-content-evenly flex-row ms-5 me-5">
      
        <form class="col-6 col-sm-12">
              <p>
                <input type="text" asp-for="SearchString"/>
                <input type="submit" value="Search" class="btn-info"/>
                <a asp-page="ViewDetails" class="mx-2">Back to list</a>
                   
                </p>
        </form>
        

        <form method="post">
            <div class="d-flex justify-content-start">
            <input type="submit" value="Export to Excel" asp-page-handler="Export" class="text-success"/>
                </div>
        </form>
 
    </div>

    
    <br />
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>
                    Email
                </th>
                <th>
                    <a asp-page="ViewDetails" class="text-black" asp-route-sortOrder="@Model.nameSort">FullName</a>
                </th>
                <th>
                    MobileNumber
                </th>
                <th>
                    Salutation
                </th>
                <th>
                    <a asp-page="ViewDetails" class="text-black" asp-route-sortOrder="@Model.genSort">Gender</a>
                </th>
                <th>
                    <a asp-page="ViewDetails" class="text-black" asp-route-sortOrder="@Model.dateSort">Date Of Birth</a>
                </th>
                <th>
                    Password
                </th>
                <th>
                    <a asp-page="ViewDetails" class="text-black" asp-route-sortOrder="@Model.modSort">Modified Date</a>
                </th>
                <th>
                    Action
                </th>


            </tr>
        </thead>

        <tbody>
            @foreach (var obj in Model.Credentials)
            {
                <tr>
                    <td width="5%">@obj.Email</td>
                    <td width="5%">@obj.FullName</td>
                    <td width="5%">@obj.MobileNumber</td>
                    <td width="5%">@obj.Salutation</td>
                    <td width="5%">@obj.Gender</td>
                    <td width="12%">@obj.DOB.ToString("MM-dd-yyyy")</td>
                    <td width="5%">@obj.Password</td>
                    <td width="12%">@obj.ModDate</td>
                    <td width="10%">
                        
                        <div class="btn-group" role="group">
                            <a asp-page="Edit" asp-route-email="@obj.Email" class="btn btn-primary btn-sm mx-2">
                                &nbsp;Edit &nbsp;

                            </a>
                            <a asp-page="Delete" asp-route-email="@obj.Email" class="btn btn-danger btn-sm ">
                                Delete
                            </a>

                        </div>

                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>
    @{
        var prevDisabled = !Model.Credentials.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.Credentials.HasNextPage ? "disabled" : "";
    }
    <a asp-page="/AllPages/ViewDetails"
       asp-route-pageIndex="@(Model.Credentials.PageIndex - 1)"
       class="btn btn-primary rounded-pill @prevDisabled">
       Previous
    </a>
    <a asp-page="/AllPages/ViewDetails"
       asp-route-pageIndex="@(Model.Credentials.PageIndex + 1)"
       class="btn btn-primary rounded-pill @nextDisabled">
        Next
    </a>
</div>